### ISSUE TITLE
Watch for comment support

### ISSUE THREAD

**Issue by jbrantly** [TypeStrong/tsconfig#14]
Just noticed that https://github.com/Microsoft/TypeScript/pull/5450 got opened which adds comment support to tsconfig.json. No clue if it will make it in, but if it does then `tsconfig` should also support.

**Comment by blakeembrey** [comment]
Added. This will be supported in the next few days here too.

**Comment by blakeembrey** [comment]
Ok, two simple solutions - use [jju](https://github.com/rlidwka/jju) (which is the fallback to display errors for `json-parse` anyway, the errors are quite good) which supports comments or use [strip-json-comments](https://github.com/sindresorhus/strip-json-comments) which works but may need a PR to replace with whitespace instead of stripping to preserve error positions.

**Comment by basarat** [comment]
jju sounds good :rose:

**Comment by blakeembrey** [comment]
@basarat My concern for that is supporting invalid syntax compared to TypeScript. I think if the whitespace fix can be applied, we should strip and replace with whitespace then parse as usual which will give us correct error positions.

**Comment by basarat** [comment]
> My concern for that is supporting invalid syntax compared to TypeScript

I'm okay with that. VSCode already supported *more* syntax than `tsc` did `¯\_(ツ)_/¯`

**Comment by jbrantly** [comment]
I was thinking the same thing. It's OK for tsconfig to be more permissive with syntax than `tsc`, but not the other way around.

**Comment by blakeembrey** [comment]
Opened both https://github.com/rlidwka/jju/issues/17 and https://github.com/sindresorhus/strip-json-comments/issues/24. Since not everyone uses `tsc`, I'd like to not accidentally support anything extra. The cleanest way for that to happen feels like stripping the comments (which is exactly what TypeScript is doing) instead of supporting JSON5.

**Comment by blakeembrey** [comment]
Merged and released with `2.2.0` :+1:
