### ISSUE TITLE
Is it actual?

### ISSUE THREAD

**Issue by whitecolor** [TypeStrong/tsconfig#28]
Noticed that `ts-node` stopped to use this module for resolving and reading config, is it still actual?

**Comment by blakeembrey** [comment]
I'm not quite sure what the question is, sorry, but yes, `ts-node` no longer depends on this module.

**Comment by whitecolor** [comment]
So why you decided not to use this module? I mean are you going to support this module, and is it going to work correctly in future?

**Comment by blakeembrey** [comment]
There's vague differences in the way `tsconfig` parses JSON vs TypeScript parsing JSON due to the internal TypeScript specific JSON parser. This results in something working with `tsc` and not working with `ts-node`. The goal was to always use the `tsc` version, but old TypeScript versions didn't expose it correctly.

The module should work in the foreseeable future and PRs are welcome, but trying to fix the minor differences and improving the errors to be in line with TypeScript would be a bit of a job. Welcome to accept a PR that does it, but right now TypeScript doesn't match any other JSON parser I know of (and even if it does, that can change later).

**Comment by whitecolor** [comment]
Ok, thanks for the elaboration.
